services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: DevOpsDenDB
    restart: always
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1456:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: API/Dockerfile  # Adjust if the Dockerfile is in a different path
    container_name: DevOpsDenAPI
    restart: always
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}   
    ports:
      - "8080:80"

volumes:
  sql_data: