version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      SA_PASSWORD: "YourStrong!Password"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: API/Dockerfile  # Adjust if the Dockerfile is in a different path
    container_name: aspnet_api
    restart: always
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=YourDbName;User Id=sa;Password=YourStrong!Password;TrustServerCertificate=True;"
    ports:
      - "8080:80"

volumes:
  sql_data: